Add solution of modal-task
js-tasks-ru/htmlcss-20230714_rsndanilov pull request #10
Opened 2023-08-16 12:12 UTC by ArsenDanilov

2023-08-16 12:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-18 11:04 UTC, GSemikozov requested changes

2023-08-18 11:04 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
Это не часть данного блока + у нас уже есть блок Кнопка

2023-08-24 11:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-24 12:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-24 12:53 UTC, ArsenDanilov commented on 05-lection3/02-modal/modal.css
> +.button {
Кнопку подключил

Но ведь в html-документе у меня и так она находится вне контейнера с модалкой. Или имеется в виду  что-то другое? Объясните, пожалуйста

2023-08-24 12:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-03 20:27 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
в блока могут быть только стили данного блока. Блок Кнопка - это блок Кнопка, не Модалка) блок Кнопка у нас уже создан и должен быть подключен в main.css. Так что из данного файла надо просто удалить .button

2023-09-03 20:27 UTC, GSemikozov requested changes

2023-09-03 20:27 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
не здась, а в main.css

2023-09-10 10:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-10 21:13 UTC, GSemikozov approved these changes

2023-09-10 21:14 UTC, merged