Add solution of radiobutton-task from homework from lecture#5
js-tasks-ru/htmlcss-20230714_rsndanilov pull request #15
Opened 2023-09-13 12:07 UTC by ArsenDanilov

Radiobutton task is ready for review

2023-09-13 12:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-14 20:13 UTC, GSemikozov requested changes

2023-09-14 20:13 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    border-color: 2px solid blue;
просто blue?)

2023-09-14 20:13 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radiobutton{
не часть блока, удалим

2023-09-15 08:22 UTC, ArsenDanilov commented on 07-lection5/02-radio/radio.css
> +    border-color: 2px solid blue;
Забыл поменять, сначала делал упражнение в CodePen, как к черновике :D

Исправил везде

2023-09-15 08:24 UTC, ArsenDanilov commented on 07-lection5/02-radio/radio.css
> +.radiobutton{
Исправил

2023-09-18 21:38 UTC, GSemikozov approved these changes

2023-09-18 21:38 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-09-18 21:39 UTC, GSemikozov approved these changes

2023-09-18 21:39 UTC, merged