Add solution of accordion-task from lecture#1 homework
js-tasks-ru/htmlcss-20230714_rsndanilov pull request #5
Opened 2023-07-27 12:31 UTC by ArsenDanilov

Добавлено решение задачи с вёрсткой аккордеона из ДЗ к лекции №1

2023-07-27 12:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-27 13:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-27 15:47 UTC, GSemikozov requested changes

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 800px;
лишнее ограничение

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    text-align: left;
так текст выравнивается по умолчанию, не обязательно прописывать

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 25px;
не по макету

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px;
мы скрыли стрелку через `display: none;`, зачем все эти свойства ниже?))

2023-07-27 15:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px;
чтобы стрелку скрыть - еще потребуется на .accordion__summary добавить list-style: none

2023-07-28 09:41 UTC, ArsenDanilov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 25px;
Подскажите, пожалуйста, где можно посмотреть необходимые параметры, чтобы делать как по макету? В Фигме не отображаются параметры для отступов. Прикрепляю скриншот 
![photo_2023-07-28_12-23-57](https://github.com/js-tasks-ru/htmlcss-20230714_rsndanilov/assets/116117200/bb21b7ce-6b2e-4674-b070-6a4c5149ca39)

2023-07-28 09:46 UTC, ArsenDanilov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
Но ведь без него внизу появляется скролл? Объясните, пожалуйста, почему его не нужно делать?

2023-07-28 09:48 UTC, ArsenDanilov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 800px;
Учёл + исправил

2023-07-28 09:48 UTC, ArsenDanilov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px;
Учёл + исправил

2023-07-28 15:00 UTC, GSemikozov requested changes

2023-07-28 15:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px;
нет, это по-прежнему здесь)

2023-07-28 15:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 25px;
<img width="72" alt="Screenshot 2023-07-28 at 17 59 44" src="https://github.com/js-tasks-ru/htmlcss-20230714_rsndanilov/assets/6191270/2224725b-8166-417a-9a4a-64a0db2e1d80">

2023-07-28 15:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
если ширина блока 100% то скрола не будет

2023-07-28 15:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 800px;
неа

2023-07-31 14:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-04 07:04 UTC, GSemikozov requested changes

2023-08-04 07:04 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0;
`margin: 16px 0 8px` или такой же паддинг

2023-08-04 08:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-04 08:51 UTC, ArsenDanilov commented
Добавлены последние правки

2023-08-11 13:20 UTC, GSemikozov approved these changes

2023-08-11 13:20 UTC, merged