Add solution for histogram-task from lecture#2 homework
js-tasks-ru/htmlcss-20230714_rsndanilov pull request #6
Opened 2023-08-04 12:59 UTC by ArsenDanilov

Добавлено решение задачи на написание гистограммы из ДЗ к лекции №2

2023-08-04 12:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-11 13:24 UTC, GSemikozov requested changes

2023-08-11 13:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 90%;
лишнее

2023-08-11 13:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
здесь - высота и марджин сверху как в макете

2023-08-11 13:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
а тут высота не нужна (ниже инлайном задаем, но в процентах относительно 50 у родителя)

2023-08-11 13:24 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__chart" style="height: 50px;"></div>
в процентах

2023-08-11 22:08 UTC, ArsenDanilov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__chart" style="height: 50px;"></div>
+

2023-08-11 22:08 UTC, ArsenDanilov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
есть

2023-08-11 22:08 UTC, ArsenDanilov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
есть

2023-08-11 22:18 UTC, ArsenDanilov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 90%;
Я сделал у тайтла flex-basis: 50% и у link flex-basis: 50%
Таким образом цифра 50254 переносится на новую строку. Без этого перенос не получается, ведь у нас неограниченная ширина контейнера

2023-08-18 11:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 90%;
Надо сгруппировать иначе - либо цифра  и заголовок плюс ссылка в отдельных контейнерах, либо объединить заголовок и цифры в одну флекс колонку

2023-09-03 20:25 UTC, GSemikozov approved these changes

2023-09-03 20:26 UTC, merged