Dz3 calendar
js-tasks-ru/htmlcss-20230714_rsndanilov pull request #8
Opened 2023-08-11 02:44 UTC by ArsenDanilov

Выполнено решение задачи на написание календаря

2023-08-11 02:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-11 13:25 UTC, GSemikozov requested changes

2023-08-11 13:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    fill: var(--white);
4-6 - почему описываем свойства для стилизации svg?

2023-08-11 13:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin: 28px 30px 40px;
наоборот, паддинги на уровне родителя, причем `28 26 32`

2023-08-11 13:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin: 24px 30px 40px;
и тогда этого не надо

2023-08-11 20:58 UTC, ArsenDanilov commented on 05-lection3/03-calendar/calendar.css
> +    fill: var(--white);
Исправил

2023-08-11 21:01 UTC, ArsenDanilov commented
Все правки учёл

2023-08-11 21:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-11 22:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-18 11:05 UTC, GSemikozov requested changes

2023-08-18 11:05 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    border-radius: 8px;
Паддинги блока - здесь

2023-08-18 11:05 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin-top: 28px;
Чтобы на уровне всех дочерних элементов не задавать вот такие марджины

2023-08-24 11:57 UTC, ArsenDanilov commented on 05-lection3/03-calendar/calendar.css
> +    border-radius: 8px;
+

2023-08-24 11:57 UTC, ArsenDanilov commented on 05-lection3/03-calendar/calendar.css
> +    margin-top: 28px;
+

2023-09-03 20:28 UTC, GSemikozov approved these changes, later dismissed

2023-09-03 20:28 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-09-03 20:29 UTC, GSemikozov approved these changes

2023-09-03 20:29 UTC, merged